In [1]:
import pandas as pd
import json
import ast
# import numpy as np

In [2]:
df = pd.read_csv("customer_behaviour_jan17_totals.csv")
df.dtypes

Unnamed: 0          int64
visitorId         float64
visitId             int64
visitStartTime      int64
date                int64
totals             object
hits               object
fullVisitorId      object
userId            float64
dtype: object

In [4]:
df

,Unnamed: 0,visitorId,visitId,visitStartTime,date,totals,hits,fullVisitorId,userId
0,0,NaN,1483290878,1483290878,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 1, 'time...","[{'hitNumber': 1, 'time': 0, 'hour': 9, 'minut...",7431279462169656568,NaN
1,1,NaN,1483293597,1483293597,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 2, 'time...","[{'hitNumber': 1, 'time': 0, 'hour': 9, 'minut...",1336484329946561874,NaN
2,2,NaN,1483292307,1483292307,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 2, 'time...","[{'hitNumber': 1, 'time': 0, 'hour': 9, 'minut...",1701623065972643878,NaN
3,3,NaN,1483299786,1483299786,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 2, 'time...","[{'hitNumber': 1, 'time': 0, 'hour': 11, 'minu...",398831489799928961,NaN
4,4,NaN,1483305691,1483305691,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 2, 'time...","[{'hitNumber': 1, 'time': 0, 'hour': 13, 'minu...",5139184322193043543,NaN
...,...,...,...,...,...,...,...,...,...
64689,64689,NaN,1485893777,1485893777,20170131,"{'visits': 1, 'hits': 64, 'pageviews': 48, 'ti...","[{'hitNumber': 1, 'time': 0, 'hour': 12, 'minu...",9534472662771201480,NaN
64690,64690,NaN,1485879620,1485879620,20170131,"{'visits': 1, 'hits': 67, 'pageviews': 47, 'ti...","[{'hitNumber': 1, 'time': 0, 'hour': 8, 'minut...",6147396474895233852,NaN
64691,64691,NaN,1485890093,1485890093,20170131,"{'visits': 1, 'hits': 70, 'pageviews': 56, 'ti...","[{'hitNumber': 1, 'time': 0, 'hour': 11, 'minu...",8436426603099391262,NaN
64692,64692,NaN,1485895299,1485895299,20170131,"{'visits': 1, 'hits': 85, 'pageviews': 81, 'ti...","[{'hitNumber': 1, 'time': 0, 'hour': 12, 'minu...",4691667039083430712,NaN
64693,64693,NaN,1485880579,1485880579,20170131,"{'visits': 1, 'hits': 154, 'pageviews': 114, '...","[{'hitNumber': 1, 'time': 0, 'hour': 8, 'minut...",4132432278764632576,NaN

In [8]:
df['hits'] = df['hits'].apply(lambda x: x[1:-1])

In [9]:
df

,Unnamed: 0,visitorId,visitId,visitStartTime,date,totals,hits,fullVisitorId,userId
0,0,NaN,1483290878,1483290878,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 1, 'time...","{'hitNumber': 1, 'time': 0, 'hour': 9, 'minute...",7431279462169656568,NaN
1,1,NaN,1483293597,1483293597,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 2, 'time...","{'hitNumber': 1, 'time': 0, 'hour': 9, 'minute...",1336484329946561874,NaN
2,2,NaN,1483292307,1483292307,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 2, 'time...","{'hitNumber': 1, 'time': 0, 'hour': 9, 'minute...",1701623065972643878,NaN
3,3,NaN,1483299786,1483299786,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 2, 'time...","{'hitNumber': 1, 'time': 0, 'hour': 11, 'minut...",398831489799928961,NaN
4,4,NaN,1483305691,1483305691,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 2, 'time...","{'hitNumber': 1, 'time': 0, 'hour': 13, 'minut...",5139184322193043543,NaN
...,...,...,...,...,...,...,...,...,...
64689,64689,NaN,1485893777,1485893777,20170131,"{'visits': 1, 'hits': 64, 'pageviews': 48, 'ti...","{'hitNumber': 1, 'time': 0, 'hour': 12, 'minut...",9534472662771201480,NaN
64690,64690,NaN,1485879620,1485879620,20170131,"{'visits': 1, 'hits': 67, 'pageviews': 47, 'ti...","{'hitNumber': 1, 'time': 0, 'hour': 8, 'minute...",6147396474895233852,NaN
64691,64691,NaN,1485890093,1485890093,20170131,"{'visits': 1, 'hits': 70, 'pageviews': 56, 'ti...","{'hitNumber': 1, 'time': 0, 'hour': 11, 'minut...",8436426603099391262,NaN
64692,64692,NaN,1485895299,1485895299,20170131,"{'visits': 1, 'hits': 85, 'pageviews': 81, 'ti...","{'hitNumber': 1, 'time': 0, 'hour': 12, 'minut...",4691667039083430712,NaN
64693,64693,NaN,1485880579,1485880579,20170131,"{'visits': 1, 'hits': 154, 'pageviews': 114, '...","{'hitNumber': 1, 'time': 0, 'hour': 8, 'minute...",4132432278764632576,NaN

In [11]:
df['hits_new'] = df['hits'].apply(lambda x: x.replace("'", '"'))
df['hits_new'] = df['hits_new'].apply(lambda x: json.loads(x))

JSONDecodeError: Expecting value: line 1 column 66 (char 65)

In [7]:
def parse_json_column(cell):
    try:
        # Replacing single quotes with double quotes to make it valid JSON
        cell = cell.replace("'", '"')
        return json.loads(cell) if pd.notnull(cell) else None
    except json.JSONDecodeError:
        return None

def parse_cols(df, name):
    return df[name].apply(parse_json_column)

In [8]:
df['device_new'] = df['device'].apply(lambda x: x.replace("'", '"'))
try: 
    df['device_new'] = df['device_new'].apply(lambda x: json.loads(x))
except json.JSONDecodeError:
    df['device_new'] = df['device_new'].apply(lambda x: ast.literal_eval(x))

df['device_new'].apply(type)

0        <class 'dict'>
1        <class 'dict'>
2        <class 'dict'>
3        <class 'dict'>
4        <class 'dict'>
              ...
64689    <class 'dict'>
64690    <class 'dict'>
64691    <class 'dict'>
64692    <class 'dict'>
64693    <class 'dict'>
Name: device_new, Length: 64694, dtype: object

In [9]:
df

,Unnamed: 0,visitorId,visitNumber,visitId,visitStartTime,date,totals,trafficSource,device,geoNetwork,customDimensions,hits,fullVisitorId,userId,channelGrouping,socialEngagementType,device_new
0,0,NaN,2,1483290878,1483290878,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 1, 'time...","{'referralPath': None, 'campaign': '(not set)'...","{'browser': 'Chrome', 'browserVersion': 'not a...","{'continent': 'Europe', 'subContinent': 'South...","[{'index': 4, 'value': 'EMEA'}]","[{'hitNumber': 1, 'time': 0, 'hour': 9, 'minut...",7431279462169656568,NaN,Organic Search,Not Socially Engaged,"{'browser': 'Chrome', 'browserVersion': 'not a..."
1,1,NaN,1,1483293597,1483293597,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 2, 'time...",{'referralPath': '/YKEI_mrn/items/c10b14f9a69f...,"{'browser': 'Safari', 'browserVersion': 'not a...","{'continent': 'Asia', 'subContinent': 'Eastern...","[{'index': 4, 'value': 'APAC'}]","[{'hitNumber': 1, 'time': 0, 'hour': 9, 'minut...",1336484329946561874,NaN,Referral,Not Socially Engaged,"{'browser': 'Safari', 'browserVersion': 'not a..."
2,2,NaN,1,1483292307,1483292307,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 2, 'time...","{'referralPath': None, 'campaign': '(not set)'...","{'browser': 'Chrome', 'browserVersion': 'not a...","{'continent': 'Americas', 'subContinent': 'Nor...","[{'index': 4, 'value': 'North America'}]","[{'hitNumber': 1, 'time': 0, 'hour': 9, 'minut...",1701623065972643878,NaN,Organic Search,Not Socially Engaged,"{'browser': 'Chrome', 'browserVersion': 'not a..."
3,3,NaN,1,1483299786,1483299786,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 2, 'time...","{'referralPath': None, 'campaign': '(not set)'...","{'browser': 'Safari', 'browserVersion': 'not a...","{'continent': 'Americas', 'subContinent': 'Nor...","[{'index': 4, 'value': 'North America'}]","[{'hitNumber': 1, 'time': 0, 'hour': 11, 'minu...",398831489799928961,NaN,Organic Search,Not Socially Engaged,"{'browser': 'Safari', 'browserVersion': 'not a..."
4,4,NaN,3,1483305691,1483305691,20170101,"{'visits': 1, 'hits': 2, 'pageviews': 2, 'time...","{'referralPath': None, 'campaign': '(not set)'...","{'browser': 'Chrome', 'browserVersion': 'not a...","{'continent': 'Americas', 'subContinent': 'Nor...","[{'index': 4, 'value': 'North America'}]","[{'hitNumber': 1, 'time': 0, 'hour': 13, 'minu...",5139184322193043543,NaN,Display,Not Socially Engaged,"{'browser': 'Chrome', 'browserVersion': 'not a..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64689,64689,NaN,7,1485893777,1485893777,20170131,"{'visits': 1, 'hits': 64, 'pageviews': 48, 'ti...","{'referralPath': '/', 'campaign': '(not set)',...","{'browser': 'Chrome', 'browserVersion': 'not a...","{'continent': 'Americas', 'subContinent': 'Nor...","[{'index': 4, 'value': 'North America'}]","[{'hitNumber': 1, 'time': 0, 'hour': 12, 'minu...",9534472662771201480,NaN,Referral,Not Socially Engaged,"{'browser': 'Chrome', 'browserVersion': 'not a..."
64690,64690,NaN,9,1485879620,1485879620,20170131,"{'visits': 1, 'hits': 67, 'pageviews': 47, 'ti...","{'referralPath': None, 'campaign': '(not set)'...","{'browser': 'Chrome', 'browserVersion': 'not a...","{'continent': 'Americas', 'subContinent': 'Nor...","[{'index': 4, 'value': 'North America'}]","[{'hitNumber': 1, 'time': 0, 'hour': 8, 'minut...",6147396474895233852,NaN,Direct,Not Socially Engaged,"{'browser': 'Chrome', 'browserVersion': 'not a..."
64691,64691,NaN,44,1485890093,1485890093,20170131,"{'visits': 1, 'hits': 70, 'pageviews': 56, 'ti...","{'referralPath': '/', 'campaign': '(not set)',...","{'browser': 'Chrome', 'browserVersion': 'not a...","{'continent': 'Americas', 'subContinent': 'Nor...","[{'index': 4, 'value': 'North America'}]","[{'hitNumber': 1, 'time': 0, 'hour': 11, 'minu...",8436426603099391262,NaN,Referral,Not Socially Engaged,"{'browser': 'Chrome', 'browserVersion': 'not a..."
64692,64692,NaN,1,1485895299,1485895299,20170131,"{'visits': 1, 'hits': 85, 'pageviews': 81, 'ti...","{'referralPath': None, 'campaign': '(not set)'...","{'browser': 'Chrome', 'browserVersion': 'not a...","{'continent': 'Americas', 'subContinent': 'Nor...","[{'index': 4, 'value': 'North America'}]","[{'hitNumber': 1, 'time': 0, 'hour': 12, 'minu...",4691667039083430712,NaN,Organic Search,Not Socially Engaged,"{'browser': 'Chrome', 'browserVersion': 'not a..."
64693,64693,NaN,2,1485880579,1485880579,20170131,"{'visits': 1, 'hits': 154, 'pageviews': 114, '...","{'referralPath': None, 'campaign': '(not set)'...","{'browser': 'Chrome', 'browserVersion': 'not a...","{'continent': 'Americas', 'subContinent': 'Nor...","[{'index': 4, 'value': 'North America'}]","[{'hitNumber': 1, 'time': 0, 'hour': 8, 'minut...",4132432278764632576,NaN,Organic Search,Not Socially Engaged,"{'browser': 'Chrome', 'browserVersion': 'not a..."

In [10]:
df['device_new'].iloc[0]

for key in ('browser', 'operatingSystem', 'isMobile', 'javaEnabled', 'deviceCategory'):
    df[key] = df['device_new'].apply(lambda x: x.get(key))

In [11]:
df = df.drop(['totals', 'trafficSource', 'device', 'geoNetwork', 'customDimensions'], axis = 1)

In [12]:
print('No. of Null Values in "javaEnabled"', df['javaEnabled'].isna().sum())
print("Dataframe dimensions", df.shape)

No. of Null Values in "javaEnabled" 64694
Dataframe dimensions (64694, 17)

In [13]:
df = df.drop(['javaEnabled'], axis = 1)

In [14]:
df2 = df.groupby(['browser'])['browser'].count()
df2

browser
Amazon Silk                      57
Android Browser                  31
Android Webview                1132
BlackBerry                       10
Chrome                        44492
Coc Coc                          53
Edge                            883
Firefox                        3078
Internet Explorer              1933
Iron                              1
LYF_LS_4002_12                    4
MRCHROME                         22
Maxthon                          20
Mozilla                           4
Mozilla Compatible Agent         46
Nintendo Browser                 21
Nokia Browser                    13
Opera                           353
Opera Mini                      530
Puffin                           19
Safari                        10382
Safari (in-app)                1206
SeaMonkey                         1
UC Browser                      222
YE                                1
YaBrowser                       179
subjectAgent: NoticiasBoom        1
Name: browser, dtype: int64

In [15]:
df3 = df.groupby(['operatingSystem'])['operatingSystem'].count()
df3

operatingSystem
(not set)          423
Android          10432
BlackBerry          13
Chrome OS         2064
Firefox OS           5
FreeBSD              3
Linux             2686
Macintosh        14779
Nintendo Wii        20
OpenBSD              2
Samsung             18
Windows          24160
Windows Phone      108
Xbox                 9
iOS               9972
Name: operatingSystem, dtype: int64

In [16]:
df4 = df.groupby(['isMobile'])['isMobile'].count()
df4

isMobile
False    43621
True     21073
Name: isMobile, dtype: int64

In [17]:
df5 = df.groupby(['deviceCategory'])['deviceCategory'].count()
df5

deviceCategory
desktop    43615
mobile     18337
tablet      2742
Name: deviceCategory, dtype: int64

In [20]:
def parse_hits(cell):
    print("handling cell", cell)
    return ast.literal_eval(cell[1:-1])

df['hits'] = df['hits'].apply(parse_hits)

handling cell [{'hitNumber': 1, 'time': 0, 'hour': 9, 'minute': 14, 'isSecure': None, 'isInteraction': True, 'isEntrance': None, 'isExit': None, 'referer': 'https://www.google.es/', 'page': {'pagePath': '/google+redesign/shop+by+brand/youtube', 'hostname': 'shop.googlemerchandisestore.com', 'pageTitle': 'YouTube | Shop by Brand | Google Merchandise Store', 'searchKeyword': None, 'searchCategory': None, 'pagePathLevel1': '/google+redesign/', 'pagePathLevel2': '/shop+by+brand/', 'pagePathLevel3': '/youtube', 'pagePathLevel4': ''}, 'transaction': None, 'item': None, 'contentInfo': None, 'appInfo': {'name': None, 'version': None, 'id': None, 'installerId': None, 'appInstallerId': None, 'appName': None, 'appVersion': None, 'appId': None, 'screenName': 'shop.googlemerchandisestore.com/google+redesign/shop+by+brand/youtube', 'landingScreenName': 'shop.googlemerchandisestore.com/google+redesign/shop+by+brand/youtube', 'exitScreenName': 'shop.googlemerchandisestore.com/google+redesign/shop+by+brand/youtube/quickview', 'screenDepth': '0'}, 'exceptionInfo': {'description': None, 'isFatal': True, 'exceptions': None, 'fatalExceptions': None}, 'eventInfo': {'eventCategory': 'Enhanced Ecommerce', 'eventAction': 'Quickview Click', 'eventLabel': 'YouTube Trucker Hat', 'eventValue': None}, 'product': array([{'productSKU': 'GGOEYHPA003510', 'v2ProductName': 'YouTube Trucker Hat', 'v2ProductCategory': 'Home/Shop by Brand/YouTube/', 'productVariant': '(not set)', 'productBrand': '(not set)', 'productRevenue': None, 'localProductRevenue': None, 'productPrice': 21990000, 'localProductPrice': 0, 'productQuantity': None, 'productRefundAmount': None, 'localProductRefundAmount': None, 'isImpression': None, 'isClick': True, 'customDimensions': array([], dtype=object), 'customMetrics': array([], dtype=object), 'productListName': 'Category', 'productListPosition': 0}],
       dtype=object), 'promotion': array([], dtype=object), 'promotionActionInfo': None, 'refund': None, 'eCommerceAction': {'action_type': '1', 'step': 1, 'option': None}, 'experiment': array([], dtype=object), 'publisher': None, 'customVariables': array([], dtype=object), 'customDimensions': array([], dtype=object), 'customMetrics': array([], dtype=object), 'type': 'EVENT', 'social': {'socialInteractionNetwork': None, 'socialInteractionAction': None, 'socialInteractions': None, 'socialInteractionTarget': None, 'socialNetwork': '(not set)', 'uniqueSocialInteractions': None, 'hasSocialSourceReferral': 'No', 'socialInteractionNetworkAction': ' : '}, 'latencyTracking': None, 'sourcePropertyInfo': None, 'contentGroup': {'contentGroup1': '(not set)', 'contentGroup2': 'Brands', 'contentGroup3': '(not set)', 'contentGroup4': '(not set)', 'contentGroup5': '(not set)', 'previousContentGroup1': '(entrance)', 'previousContentGroup2': '(entrance)', 'previousContentGroup3': '(entrance)', 'previousContentGroup4': '(entrance)', 'previousContentGroup5': '(entrance)', 'contentGroupUniqueViews1': None, 'contentGroupUniqueViews2': None, 'contentGroupUniqueViews3': None, 'contentGroupUniqueViews4': None, 'contentGroupUniqueViews5': None}, 'dataSource': None, 'publisher_infos': array([], dtype=object)}
 {'hitNumber': 2, 'time': 0, 'hour': 9, 'minute': 14, 'isSecure': None, 'isInteraction': True, 'isEntrance': True, 'isExit': True, 'referer': 'https://www.google.es/', 'page': {'pagePath': '/google+redesign/shop+by+brand/youtube/quickview', 'hostname': 'shop.googlemerchandisestore.com', 'pageTitle': 'YouTube | Shop by Brand | Google Merchandise Store', 'searchKeyword': None, 'searchCategory': None, 'pagePathLevel1': '/google+redesign/', 'pagePathLevel2': '/shop+by+brand/', 'pagePathLevel3': '/youtube/', 'pagePathLevel4': '/quickview'}, 'transaction': None, 'item': None, 'contentInfo': None, 'appInfo': {'name': None, 'version': None, 'id': None, 'installerId': None, 'appInstallerId': None, 'appName': None, 'appVersion': None, 'appId': None, 'screenName': 'shop.googlemerchandisestore.com/google+redesign/shop+by+brand/youtube/quickview', 'landingScreenName': 'shop.googlemerchandisestore.com/google+redesign/shop+by+brand/youtube', 'exitScreenName': 'shop.googlemerchandisestore.com/google+redesign/shop+by+brand/youtube/quickview', 'screenDepth': '0'}, 'exceptionInfo': {'description': None, 'isFatal': True, 'exceptions': None, 'fatalExceptions': None}, 'eventInfo': None, 'product': array([{'productSKU': 'GGOEYHPA003510', 'v2ProductName': 'YouTube Trucker Hat', 'v2ProductCategory': 'Home/Shop by Brand/YouTube/', 'productVariant': '(not set)', 'productBrand': '(not set)', 'productRevenue': None, 'localProductRevenue': None, 'productPrice': 21990000, 'localProductPrice': 0, 'productQuantity': None, 'productRefundAmount': None, 'localProductRefundAmount': None, 'isImpression': None, 'isClick': None, 'customDimensions': array([], dtype=object), 'customMetrics': array([], dtype=object), 'productListName': 'Category', 'productListPosition': 1}],
       dtype=object), 'promotion': array([], dtype=object), 'promotionActionInfo': None, 'refund': None, 'eCommerceAction': {'action_type': '2', 'step': 1, 'option': None}, 'experiment': array([], dtype=object), 'publisher': None, 'customVariables': array([], dtype=object), 'customDimensions': array([], dtype=object), 'customMetrics': array([], dtype=object), 'type': 'PAGE', 'social': {'socialInteractionNetwork': None, 'socialInteractionAction': None, 'socialInteractions': None, 'socialInteractionTarget': None, 'socialNetwork': '(not set)', 'uniqueSocialInteractions': None, 'hasSocialSourceReferral': 'No', 'socialInteractionNetworkAction': ' : '}, 'latencyTracking': None, 'sourcePropertyInfo': None, 'contentGroup': {'contentGroup1': 'YouTube', 'contentGroup2': 'Brands', 'contentGroup3': '(not set)', 'contentGroup4': '(not set)', 'contentGroup5': '(not set)', 'previousContentGroup1': '(not set)', 'previousContentGroup2': 'Brands', 'previousContentGroup3': '(not set)', 'previousContentGroup4': '(not set)', 'previousContentGroup5': '(not set)', 'contentGroupUniqueViews1': 1, 'contentGroupUniqueViews2': 1, 'contentGroupUniqueViews3': None, 'contentGroupUniqueViews4': None, 'contentGroupUniqueViews5': None}, 'dataSource': None, 'publisher_infos': array([], dtype=object)}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]

IndentationError: unexpected indent (<unknown>, line 3)